id: tof_camera
name: ToF Camera
name[zh]: ToF相机
version: 1.0.0
icon: assets/tof.json
author: Sipeed Ltd
desc: ToF
desc[zh]: ToF
files:
  app.yaml: app.yaml
  assets: assets
  README.md: README.md
  README_EN.md: README_EN.md

